global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.125.42.41:9100']
  - job_name: aws-cost-exporter-metrics
    scrape_interval: 80s
    scrape_timeout: 60s
    static_configs:
      - targets: ['3.125.42.41:5000']